[phases.setup]
nixPkgs = ["php82Extensions.bcmath", "php82Extensions.zip", "php82Extensions.exif", "php82Extensions.gd"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = []
